// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: examples/app/api/greeter/v1/greeter.proto

package greeterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_examples_app_api_greeter_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ServedAt      string                 `protobuf:"bytes,4,opt,name=served_at,json=servedAt,proto3" json:"served_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_examples_app_api_greeter_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SayHelloResponse) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *SayHelloResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SayHelloResponse) GetServedAt() string {
	if x != nil {
		return x.ServedAt
	}
	return ""
}

type GetGreetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGreetingRequest) Reset() {
	*x = GetGreetingRequest{}
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGreetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetingRequest) ProtoMessage() {}

func (x *GetGreetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetingRequest.ProtoReflect.Descriptor instead.
func (*GetGreetingRequest) Descriptor() ([]byte, []int) {
	return file_examples_app_api_greeter_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *GetGreetingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGreetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGreetingResponse) Reset() {
	*x = GetGreetingResponse{}
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGreetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetingResponse) ProtoMessage() {}

func (x *GetGreetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetingResponse.ProtoReflect.Descriptor instead.
func (*GetGreetingResponse) Descriptor() ([]byte, []int) {
	return file_examples_app_api_greeter_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *GetGreetingResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetGreetingResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_examples_app_api_greeter_v1_greeter_proto_rawDescGZIP(), []int{4}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	StartedAt     string                 `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Requests      int64                  `protobuf:"varint,5,opt,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_app_api_greeter_v1_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_examples_app_api_greeter_v1_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *InfoResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *InfoResponse) GetRequests() int64 {
	if x != nil {
		return x.Requests
	}
	return 0
}

var File_examples_app_api_greeter_v1_greeter_proto protoreflect.FileDescriptor

const file_examples_app_api_greeter_v1_greeter_proto_rawDesc = "" +
	"\n" +
	")examples/app/api/greeter/v1/greeter.proto\x12\n" +
	"greeter.v1\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"}\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1b\n" +
	"\tserved_at\x18\x04 \x01(\tR\bservedAt\"$\n" +
	"\x12GetGreetingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"9\n" +
	"\x13GetGreetingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\r\n" +
	"\vInfoRequest\"\x9e\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12\x1a\n" +
	"\brequests\x18\x05 \x01(\x03R\brequests2\xdb\x01\n" +
	"\aGreeter\x12E\n" +
	"\bSayHello\x12\x1b.greeter.v1.SayHelloRequest\x1a\x1c.greeter.v1.SayHelloResponse\x12N\n" +
	"\vGetGreeting\x12\x1e.greeter.v1.GetGreetingRequest\x1a\x1f.greeter.v1.GetGreetingResponse\x129\n" +
	"\x04Info\x12\x17.greeter.v1.InfoRequest\x1a\x18.greeter.v1.InfoResponseBFZDgithub.com/Tokimorphling/gosvc/examples/app/api/greeter/v1;greeterv1b\x06proto3"

var (
	file_examples_app_api_greeter_v1_greeter_proto_rawDescOnce sync.Once
	file_examples_app_api_greeter_v1_greeter_proto_rawDescData []byte
)

func file_examples_app_api_greeter_v1_greeter_proto_rawDescGZIP() []byte {
	file_examples_app_api_greeter_v1_greeter_proto_rawDescOnce.Do(func() {
		file_examples_app_api_greeter_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_app_api_greeter_v1_greeter_proto_rawDesc), len(file_examples_app_api_greeter_v1_greeter_proto_rawDesc)))
	})
	return file_examples_app_api_greeter_v1_greeter_proto_rawDescData
}

var file_examples_app_api_greeter_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_examples_app_api_greeter_v1_greeter_proto_goTypes = []any{
	(*SayHelloRequest)(nil),     // 0: greeter.v1.SayHelloRequest
	(*SayHelloResponse)(nil),    // 1: greeter.v1.SayHelloResponse
	(*GetGreetingRequest)(nil),  // 2: greeter.v1.GetGreetingRequest
	(*GetGreetingResponse)(nil), // 3: greeter.v1.GetGreetingResponse
	(*InfoRequest)(nil),         // 4: greeter.v1.InfoRequest
	(*InfoResponse)(nil),        // 5: greeter.v1.InfoResponse
}
var file_examples_app_api_greeter_v1_greeter_proto_depIdxs = []int32{
	0, // 0: greeter.v1.Greeter.SayHello:input_type -> greeter.v1.SayHelloRequest
	2, // 1: greeter.v1.Greeter.GetGreeting:input_type -> greeter.v1.GetGreetingRequest
	4, // 2: greeter.v1.Greeter.Info:input_type -> greeter.v1.InfoRequest
	1, // 3: greeter.v1.Greeter.SayHello:output_type -> greeter.v1.SayHelloResponse
	3, // 4: greeter.v1.Greeter.GetGreeting:output_type -> greeter.v1.GetGreetingResponse
	5, // 5: greeter.v1.Greeter.Info:output_type -> greeter.v1.InfoResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_app_api_greeter_v1_greeter_proto_init() }
func file_examples_app_api_greeter_v1_greeter_proto_init() {
	if File_examples_app_api_greeter_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_app_api_greeter_v1_greeter_proto_rawDesc), len(file_examples_app_api_greeter_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_app_api_greeter_v1_greeter_proto_goTypes,
		DependencyIndexes: file_examples_app_api_greeter_v1_greeter_proto_depIdxs,
		MessageInfos:      file_examples_app_api_greeter_v1_greeter_proto_msgTypes,
	}.Build()
	File_examples_app_api_greeter_v1_greeter_proto = out.File
	file_examples_app_api_greeter_v1_greeter_proto_goTypes = nil
	file_examples_app_api_greeter_v1_greeter_proto_depIdxs = nil
}
