// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package echo

import (
	"context"
	"fmt"
)

type EchoService interface {
	Echo(ctx context.Context, message string) (r string, err error)
}

type EchoServiceEchoArgs struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
}

func NewEchoServiceEchoArgs() *EchoServiceEchoArgs {
	return &EchoServiceEchoArgs{}
}

func (p *EchoServiceEchoArgs) InitDefault() {
}

func (p *EchoServiceEchoArgs) GetMessage() (v string) {
	return p.Message
}
func (p *EchoServiceEchoArgs) SetMessage(val string) {
	p.Message = val
}

func (p *EchoServiceEchoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoServiceEchoArgs(%+v)", *p)
}

var fieldIDToName_EchoServiceEchoArgs = map[int16]string{
	1: "message",
}

type EchoServiceEchoResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewEchoServiceEchoResult() *EchoServiceEchoResult {
	return &EchoServiceEchoResult{}
}

func (p *EchoServiceEchoResult) InitDefault() {
}

var EchoServiceEchoResult_Success_DEFAULT string

func (p *EchoServiceEchoResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return EchoServiceEchoResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *EchoServiceEchoResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *EchoServiceEchoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoServiceEchoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoServiceEchoResult(%+v)", *p)
}

var fieldIDToName_EchoServiceEchoResult = map[int16]string{
	0: "success",
}
